import { readFileSync, writeFileSync } from 'node:fs';

const src = readFileSync('src/data/mobs.ts', 'utf8');
const ids = [...src.matchAll(/'minecraft:[^']+'/g)].map((m) => m[0].slice(1, -1));

const da = {
  'minecraft:allay': 'Hjælper',
  'minecraft:armadillo': 'Bæltedyr',
  'minecraft:axolotl': 'Axolotl',
  'minecraft:bat': 'Flagermus',
  'minecraft:bee': 'Bi',
  'minecraft:blaze': 'Blaze',
  'minecraft:bogged': 'Sumpzombie',
  'minecraft:breeze': 'Vindstød',
  'minecraft:camel': 'Kamel',
  'minecraft:cat': 'Kat',
  'minecraft:cave_spider': 'Huleedderkop',
  'minecraft:chicken': 'Kylling',
  'minecraft:cod': 'Torsk',
  'minecraft:cow': 'Ko',
  'minecraft:creaking': 'Knirker',
  'minecraft:creeper': 'Creeper',
  'minecraft:dolphin': 'Delfin',
  'minecraft:donkey': 'Æsel',
  'minecraft:drowned': 'Draug',
  'minecraft:elder_guardian': 'Gammel vogter',
  'minecraft:enderman': 'Enderman',
  'minecraft:endermite': 'Endermite',
  'minecraft:ender_dragon': 'Enderdrage',
  'minecraft:evoker': 'Tilkaldere',
  'minecraft:fox': 'Ræv',
  'minecraft:frog': 'Frø',
  'minecraft:ghast': 'Ghast',
  'minecraft:giant': 'Kæmpe',
  'minecraft:glow_squid': 'Lysblæksprutte',
  'minecraft:goat': 'Ged',
  'minecraft:guardian': 'Vogter',
  'minecraft:hoglin': 'Hoglin',
  'minecraft:horse': 'Hest',
  'minecraft:husk': 'Udtørret zombie',
  'minecraft:illusioner': 'Illusionist',
  'minecraft:iron_golem': 'Jern golem',
  'minecraft:llama': 'Lama',
  'minecraft:magma_cube': 'Magmaklump',
  'minecraft:mooshroom': 'Mooshroom',
  'minecraft:mule': 'Muldyr',
  'minecraft:ocelot': 'Ozelot',
  'minecraft:panda': 'Panda',
  'minecraft:parrot': 'Papegøje',
  'minecraft:phantom': 'Fantom',
  'minecraft:pig': 'Gris',
  'minecraft:piglin': 'Piglin',
  'minecraft:piglin_brute': 'Piglin bølle',
  'minecraft:pillager': 'Plyndrer',
  'minecraft:polar_bear': 'Isbjørn',
  'minecraft:pufferfish': 'Kuglefisk',
  'minecraft:rabbit': 'Kanin',
  'minecraft:ravager': 'Hærger',
  'minecraft:salmon': 'Laks',
  'minecraft:sheep': 'Får',
  'minecraft:shulker': 'Shulker',
  'minecraft:silverfish': 'Sølvfisk',
  'minecraft:skeleton': 'Skelet',
  'minecraft:skeleton_horse': 'Skelethest',
  'minecraft:slime': 'Slim',
  'minecraft:sniffer': 'Sniffer',
  'minecraft:snow_golem': 'Snemand',
  'minecraft:spider': 'Edderkop',
  'minecraft:squid': 'Blæksprutte',
  'minecraft:stray': 'Omstrejfer',
  'minecraft:strider': 'Lavavandrer',
  'minecraft:tadpole': 'Haletudse',
  'minecraft:trader_llama': 'Købmandslama',
  'minecraft:tropical_fish': 'Tropisk fisk',
  'minecraft:turtle': 'Skildpadde',
  'minecraft:vex': 'Vex',
  'minecraft:villager': 'Landsbyboer',
  'minecraft:vindicator': 'Hævner',
  'minecraft:wandering_trader': 'Omstrejfende købmand',
  'minecraft:warden': 'Vogter',
  'minecraft:witch': 'Heks',
  'minecraft:wither': 'Wither',
  'minecraft:wither_skeleton': 'Witherskelet',
  'minecraft:wolf': 'Ulv',
  'minecraft:zoglin': 'Zoglin',
  'minecraft:zombie': 'Zombie',
  'minecraft:zombie_horse': 'Zombiehest',
  'minecraft:zombie_villager': 'Zombie landsbyboer',
  'minecraft:zombified_piglin': 'Zombificeret piglin',
};

function mobLabelEn(id) {
  return id
    .replace(/^minecraft:/, '')
    .split('_')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

const en = {};
for (const id of ids) {
  const key = id.replace('minecraft:', '');
  en[key] = mobLabelEn(id);
  if (!da[id]) da[id] = en[key];
}

const daOut = {};
for (const id of ids) {
  daOut[id.replace('minecraft:', '')] = da[id];
}

writeFileSync(
  'src/i18n/locales/mobs.generated.ts',
  `// Auto-generated by scripts/gen-mobs-da.mjs — do not edit by hand\n\nexport const mobsEn = ${JSON.stringify(en, null, 2)} as const;\n\nexport const mobsDa = ${JSON.stringify(daOut, null, 2)} as const;\n`,
);
